# Migration guide: https://developer.android.google.cn/build/migrate-to-catalogs

[versions]
# ======================== Google Official Extension ========================

androidGradlePlugin = "8.1.1"

# Core
ktx = "1.10.1"
appcompat = "1.6.1"
activityCompose = "1.7.2"
espressoCore = "3.5.1"
constraintlayout = "2.1.4"

# Junit
junit = "4.13.2"
junitVersion = "1.1.5"

# Compose
androidxComposeBom = "2023.08.00"

# Accompanist Components
accompanist = "0.31.2-alpha"

# Navigation
navigationCompose = "2.7.1"
hiltNavigationCompose = "1.0.0"

# Lifecycle
lifecycleExtensions = "2.2.0"
lifecycleRuntimeCompose = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
lifecycleLivedataKtx = "2.6.1"
lifecycleRuntimeKtx = "2.6.1"

# Datastore
datastore = "1.0.0"
datastorePreferences = "1.0.0"

# Room
playServicesAuth = "20.7.0"
playServicesAds = "22.3.0"
playServicesLocation = "21.0.1"
pagingCompose = "3.2.0"
pagingCommonKtx = "3.2.0"
pagingRuntimeKtx = "3.2.0"
retrofit = "2.9.0"
roomKtx = "2.5.2"
roomRuntime = "2.5.2"
roomCompiler = "2.5.2"
roomTesting = "2.5.2"
workMultiprocess = "2.8.1"
workTesting = "2.8.1"
workGcm = "2.8.1"
workRuntimeKtx = "2.8.1"
workRuntime = "2.8.1"

# Gson
gson = "2.10.1"

# Hilt
hiltAndroid = "2.47"
hiltCompiler = "2.47"
hiltWork = "1.0.0"

# Coroutine-ktx
kotlinxCoroutinesCore = "1.7.1"
kotlinxCoroutinesAndroid = "1.7.1"
kotlinxCoroutinesTest = "1.7.1"

# Gogole Services
googleServices = "4.3.15"

# Firebase
firebaseBom = "32.2.3"
firebaseCrashlyticsGradle = "2.9.9"
firebasePerfPlugin = "1.4.2"

# ======================== Third-party Extension ========================

# Coil
coilCompose = "2.4.0"

# Moshi
moshi = "1.15.0"
moshiAdapters = "1.15.0"
converterMoshi = "2.9.0"
moshiKotlinCodegen = "1.15.0"

# Lottie
lottieCompose = "6.0.0"

[libraries]
accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "pagingCommonKtx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workMultiprocess" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "workGcm" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf-plugin = { module = "com.google.firebase:perf-plugin", version.ref = "firebasePerfPlugin" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshiAdapters" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-testing = { module = "androidx.room:room-testing", version.ref = "roomTesting" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }