# Migration guide: https://developer.android.google.cn/build/migrate-to-catalogs

[versions]
ktx = "1.10.1"
androidGradlePlugin = "8.1.1"

[libraries]
android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }